runtime: nodejs18

handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html

env_variables:
  REACT_APP_BASE_URL: "https://pokedex-frontend-froggy.uw.r.appspot.com"
  REACT_APP_API_BASE_URL: "https://pokedex-backend-froggy.uw.r.appspot.com"
  REACT_APP_GOOGLE_CLIENT_ID: "821039126740-tmjqo1dagivarr4kqie4b6phnem5arcn.apps.googleusercontent.com"
  REACT_APP_GOOGLE_CLIENT_SECRET: "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"